### ISSUE TITLE
训练完了，但模型没有保存

### ISSUE THREAD

**Issue by zyb8543d** [huynq2k4/XTTS-finetune#1]
什么情况，只有这四个文件
```
-rw-r--r-- 1 root root  5500 Dec  2 09:48 config.json
-rw-r--r-- 1 root root 21627 Dec  2 10:01 events.out.tfevents.1733132905.master.271.0
-rw-r--r-- 1 root root  9910 Dec  2 09:48 train_gpt_xtts.py
-rw-r--r-- 1 root root  7942 Dec  2 10:01 trainer_0_log.txt
```

**Comment by huynq2k4** [comment]
Actually my repo is cloned from the following repo: https://github.com/nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages.git. I used it for my university class project, and some changes are not done directly on this repo. You can make a new issue in the above repo to get more information. Thank you very much!
